### ISSUE TITLE
Version upgrade issue

### ISSUE THREAD

**Issue by shrkx** [emiago/sipgo#167]
github.com/emiago/sipgo v0.25.0  => github.com/emiago/sipgo v0.27.0

Call forwarding and message forwarding are completely disconnected

**Comment by shrkx** [comment]
![1734694588755](https://github.com/user-attachments/assets/52fb4416-780d-47e0-834a-acd2ce228013)


I have forwarded it, but I haven't received it yet

**Comment by emiago** [comment]
Hi @shrkx . Thanks for reporting.
 Can you be more specific. I am not sure what I am looking here. 

What is disconnected? What should I look in that image?

**Comment by shrkx** [comment]
github.com/emiago/sipgo v0.25.0 => github.com/emiago/sipgo v0.27.0

@emiago 


The code has not been modified at all, only the version has been upgraded. The result is forwarding, but the forwarding has not been received. However, according to the logs, there are forwarding logs, but there is no response after forwarding, so we don't know what the situation is

**Comment by shrkx** [comment]
![1734853287319](https://github.com/user-attachments/assets/8d255a4b-c85d-4110-9e7a-4ae581f28eba)
![1734853314388](https://github.com/user-attachments/assets/0f7f1a4f-7716-4d45-99c6-d3e863660155)


The logs of sending and forwarding can be seen, but there is no response from the forwarding client,

**Comment by emiago** [comment]
Hi @shrkx . I am really wondering are you doing things right. I see 2 connections here on your 5060, but first Via header makes no sense if this is just all local. 
And second is sent via other connection. 

Please explain what are you doing, I see record route header, what is this message passing and how. 
What is expected behavior?
Please double check your connections (ports) on receiving side as well as SIP Debug reports a moment before it flies through network, so it is mostly correct.

**Comment by shrkx** [comment]
Two local SIP phones were used to forward messages and signaling between each other. Before the upgrade, forwarding was possible, but after the upgrade, all forwarding was not forwarded. However, printing logs was done by forwarding, but if it was not received, the sender would prompt a timeout

**Comment by emiago** [comment]
Hi @shrkx , I fail to see what could be issue. I suggest that this needs more debugging. 
Please also understad any non English here logs I will not read and try to use some standard tools like sngrep or SIPDebug=true. 
Confirm that it is not some network issue. 
If the issue is really in libs, you must be able to discover/show some difference.

**Comment by shrkx** [comment]
![image](https://github.com/user-attachments/assets/47f41c60-231d-47ea-a0cd-902adc33b71b)
Please refer to this image 192.168.3.105:5060<-192.168.3.105:59735, which shows the operation of Client 1 sending a message to the SIP server,
192.168.3.105:5060->192.168.3.105:54471 Then SIP signaling forwarded the message to client 2, but the forwarding result was not received, so client 1 received a timeout prompt

**Comment by emiago** [comment]
Hi @shrkx , generally this messaging happens before going out on network. So I can not see what is wrong. 
I suggest confirming on your client 2 is there some issue or if you doubt, use any network tracing and generate PCAP. 

What I would like to see is your difference old version and new version.
Can you use fixed ports and not empheral? Maybe some firewall is issue?
