### ISSUE TITLE
Race condition when handling multiple repsonses

### ISSUE THREAD

**Issue by florisk** [emiago/sipgo#89]
Hi,
While working on adding re-INVITE logic to the `DialogServer` and `DialogClient` I found the `dialog_integration_test.go` to be failing with a deadlock.

On further investigation I turned out that while waiting for a 200 response in a `WaitAnswer` the 200 response is never received.
The `lastResp` in `commonTx` is set in `func (tx *ClientTx) receive(res *Response) error` and read and pushed to the `tx.responses` channel in `func (tx *ClientTx) passUp() ` 
In the test cases sending a 100,180 and 200 response without any delays sometimes causes 200 response not to be received.

I did not look into a solution yet. But looking at the comments  on`func (txl *TransactionLayer) handleMessage(msg Message)`  I understand you have given this a look. 
I think reordering of messages might not be an issues, this might also happen on the network or with re-transmits, but loosing messages might be more of a concern.  
Any thoughts on a solution ?

I see a couple of possible directions:
* rework the locking, but that might be real complex .
* use an array for `lastResp` to ensure we don't loose any reponses.
* use separate variables to hold transient responses (1XX) and final responses.

I provided a test case for this here [https://github.com/florisk/sipgo/blob/client-transaction-racecondition/sip/transaction_client_tx_test.go#L61](url)

**Comment by emiago** [comment]
Hi @florisk . Thanks for hunting this down. 
First yes, there was some fixes arround this and improvements, but yes now I understand order is now lost. 
Interesting is that I so far did not detect this.

There should not be message lost unless your transaction timed out. So I wonder is this the case. 

Quick fix would be introducing channel buffering, but the intially I avoided this in order to find more racing and avoid message lost.
With buffering it is logical that you have start dropping message at some point. 

I see also some middleground. Will think about it. 

Thanks for reporting. 

BTW test is confusing, and you have to do this from transaction layer as this is where forking is happening. 
Every message is goroutine ;)

**Comment by florisk** [comment]
Let me elaborate a bit more on the issue and the test. 
This is the normal flow when receiving response.
1. A response message is received in the transport  layer calls. The `func (l *TransportLayer) OnMessage(h MessageHandler)` calls the registered  `func (txl *TransactionLayer) handleMessage(msg Message)`
2. The `handleMessage` will start a go routine for `func (txl *TransactionLayer) handleResponse(res *Response)`
3. The `handleResponse` calls `func (tx *ClientTx) receive(res *Response) error`.  This is the starting point in the test case. ( [line 101](https://github.com/florisk/sipgo/blob/743b3016990c5a53fd7df2dd367d25ea459befbc/sip/transaction_client_tx_test.go#L101)
4. The `receive` method stores the response in the `lastResp` variable and stats processing the state with `func (tx *commonTx) spinFsm(in fsmInput)`
5. During the processing of the state `func (tx *ClientTx) passUp()` is called.
6. The `passUp` reads the `lastResp` and puts it on the `tx.responses` channel.
7. On an other go routine the `(tx *ClientTx) Responses()` channel is used to wait for a response. For instance `func (s *DialogClientSession) WaitAnswer(ctx context.Context, opts AnswerOptions) error` See [Line 93](https://github.com/florisk/sipgo/blob/743b3016990c5a53fd7df2dd367d25ea459befbc/sip/transaction_client_tx_test.go#L93) in the test case.

This race condition is as fowllows:
1.  consider two go routines handling two messages (100,200) with a short interval. 
2. the go routines are scheduled in the wrong order. 
3. The 200 routine store the response in `lastResp` (Step 4).
4. The 100 routine store the response in `lastResp` (Step 4).
5. The 200 routine calls `passUp` and writes the incorrect 100 response (for this go routine) on the channel.
6. The 100 routine calls `passUp` and writes the correct 100 response on the channel.

In the [TestIntegrationDialog WaitAnser](https://github.com/florisk/sipgo/blob/743b3016990c5a53fd7df2dd367d25ea459befbc/dialog_integration_test.go#L114) we block on waiting for the 200 response.
If we used a deadline, we would have gotten an error. But since this test cases does not use a deadline, the test fails on timeout with the following trace.
[trace.log](https://github.com/emiago/sipgo/files/15388124/trace.log)

In production code using a `WaitAnser` without a deadline would be mistake, but this race condition may cause transactions to fail even though the correct response was received.

The provided test sends a lot of messages and checks if each message is received once.

**Comment by emiago** [comment]
Hi @florisk Thanks for detail report. Now I understand where is issue. Will check it out. 

Previously there was forking only when FSM is passing message up, but now I see this broke.

**Comment by emiago** [comment]
Hi @florisk pls check main branch (latest commit)

So I refactored currently so that reading resp is protected by fsm lock and prefixed mostly this fields with `fsm`
This basically prevents loss of messages and keeps state changing protected. 

Blocking is left. It is expected client consumes messages or it terminates. 

Similar for server but there ack and cancel still specially handled. Reason is that to allow termination/error flowing sooner. 

There is room for improvements, but for now keeping smaller updates. Benchmarks did not show any drop, maybe even there is now less locking.
Thanks for reporting again. 

Let me know does last fix solves issue.
